apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-design-kata
spec:
  replicas: 3
  selector:
    matchLabels:
      app: system-design-kata
  template:
    metadata:
      labels:
        app: system-design-kata
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: systemdesignkataacr.azurecr.io/system-design-kata-edge-device:21927d0394a3040ad376b2a5d614b5280806787b
          name: edge-device
          env:
            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: system-design-kata-secret
                  key: ServiceBus__ConnectionString
            - name: ServiceBus__TopicName
              valueFrom:
                secretKeyRef:
                  name: system-design-kata-secret
                  key: ServiceBus__TopicName
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
        - image: systemdesignkataacr.azurecr.io/system-design-kata-message-processor:21927d0394a3040ad376b2a5d614b5280806787b
          name: message-processor
          env:
            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: system-design-kata-secret
                  key: ServiceBus__ConnectionString
            - name: ServiceBus__TopicName
              valueFrom:
                secretKeyRef:
                  name: system-design-kata-secret
                  key: ServiceBus__TopicName
            - name: ServiceBus__SubscriptionName
              valueFrom:
                secretKeyRef:
                  name: system-design-kata-secret
                  key: ServiceBus__SubscriptionName
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
