apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-design-kata
spec:
  selector:
    matchLabels:
      app: system-design-kata
  template:
    metadata:
      labels:
        app: system-design-kata
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: systemdesignkataacr.azurecr.io/system-design-kata-edge-device:b7aaa88c4db73aeeb56dde9c2cc57ba0222264f2
          name: edge-device
          env:
            - name: ServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: system-design-kata-secret
                  key: ServiceBus__ConnectionString
            - name: ServiceBus__TopicName
              valueFrom:
                secretKeyRef:
                  name: system-design-kata-secret
                  key: ServiceBus__TopicName
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
