apiVersion: v1
kind: Secret
metadata:
  name: system-design-kata-secret
type: Opaque
data:
  ServiceBus__ConnectionString: "AZURE SERVICE BUS CONNECTION STRING"
  ServiceBus__TopicName: "AZURE SERVICE BUS TOPIC NAME"
