name: Build and Deploy to Azure Container Instances

on:
 workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true
        
    - name: Build and push image
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -f ./be/docker/EdgeDevice.dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/system-design-kata-edge-device:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/system-design-kata-edge-device:${{ github.sha }}
    # # Deploy to Azure Container Instances
    # - name: Deploy to Azure Container Instances
    #   run: |
    #     az container create \
    #       --resource-group MyResourceGroup \
    #       --name my-container-instance \
    #       --image MyRegistryName.azurecr.io/yourapp:latest \
    #       --registry-login-server MyRegistryName.azurecr.io \
    #       --registry-username ${{ secrets.ACR_USERNAME }} \
    #       --registry-password ${{ secrets.ACR_PASSWORD }} \
    #       --cpu 1 \
    #       --memory 1 \
    #       --port 80
